FROM node:20-alpine as build

WORKDIR /app
# 设置npm使用国内镜像源
RUN npm config set registry https://registry.npmmirror.com

COPY web/. ./
RUN npm install

RUN npm run build

FROM nginx:alpine as runtime

# 复制 SSL 证书
COPY ssl/sanora.linkwe-inc.com.pem /etc/nginx/ssl/
COPY ssl/sanora.linkwe-inc.com.key /etc/nginx/ssl/

# 复制 nginx 配置
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

# 复制前端构建产物
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
